### ISSUE TITLE
Please fix update.json

### ISSUE THREAD

**Issue by IzzySoft** [CrazyBytesVE/GMS-Doze#2]
The `update.json` contained in the ZIP is broken. Could you please remove the trailing comma there (after the changelog) so parsing it no longer fails?

```json
{
    "version": "1.3A",
    "versionCode": 130,
    "zipUrl": "https://github.com/CrazyBytesVE/GMS-Doze/releases/download/V1.3A/GMS.Doze.V1.3A.zip",
    "changelog": "https://github.com/CrazyBytesVE/GMS-Doze/blob/GMS-Doze/changelog.md",
}
```

Thanks!

**Comment by CrazyBytesVE** [comment]
> The `update.json` contained in the ZIP is broken. Could you please remove the trailing comma there (after the changelog) so parsing it no longer fails?
> 
> ```json
> {
>     "version": "1.3A",
>     "versionCode": 130,
>     "zipUrl": "https://github.com/CrazyBytesVE/GMS-Doze/releases/download/V1.3A/GMS.Doze.V1.3A.zip",
>     "changelog": "https://github.com/CrazyBytesVE/GMS-Doze/blob/GMS-Doze/changelog.md",
> }
> ```
> 
> Thanks!

Fixed bug in update.json

Thanks!

**Comment by IzzySoft** [comment]
Thank you!
